"""rename department

Revision ID: b999d83e1b6c
Revises: ccf5e6431d03
Create Date: 2026-02-13 22:53:12.035130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b999d83e1b6c'
down_revision = 'ccf5e6431d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department','departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments','department')
    # ### end Alembic commands ###
