"""rename address

Revision ID: db514950c0f7
Revises: b999d83e1b6c
Create Date: 2026-02-13 23:13:33.486699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db514950c0f7'
down_revision = 'b999d83e1b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.alter_column('departments', 'address',  new_column_name='location')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
